# Generated by Django 2.2.4 on 2019-08-31 10:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dynamo_id', models.CharField(max_length=200)),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='own_charts', to=settings.AUTH_USER_MODEL)),
                ('member', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
