# Generated by Django 2.2.4 on 2019-08-31 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0002_auto_20190831_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='chart',
            name='name',
            field=models.CharField(default='mandalart chart', max_length=200),
        ),
    ]
