# Generated by Django 2.2.4 on 2019-08-31 11:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0003_chart_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='member',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
