# Generated by Django 2.2.4 on 2019-08-31 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0004_auto_20190831_1136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chart',
            name='name',
        ),
    ]
